### ISSUE TITLE
Unable to delete/detach network interfaces and NLB($$)

### ISSUE THREAD

**Issue by emcginty70** [aws-samples/aws-modern-application-workshop#93] opened 2019-03-28 16:27 UTC
I'm suffering with a common issue, I cant delete the NLB and I'm getting charged.  I've followed the recommendations and deleted the ECS cluster, cloudwatch logs, and tried to disassociate the NLB from the endpoint service but no luck.  I've had no luck removing the NLB from the endpoint service.  I also tried the cloudformation stack and no luck either. 

VPC >> vpc-0ef3a3953e60205e2

EndpointServices >> com.amazonaws.vpce.us-east-1.vpce-svc-0b127c49ecfc55422

NLB >> arn:aws:elasticloadbalancing:us-east-1:281174624655:loadbalancer/net/mysfits-nlb/eb9c86e32cfc83b6

**Comment by abaird986** [comment] 2019-03-29 14:43
Hi @emcginty70  - we're not able to view any of your resources to provide guidance, AWS Support would be able to help if you're on a support plan and create a case, or if you post this issue to the AWS Forums.

However, if you provide the error returned, I can try and provide some more specific guidance. Usually this is caused by the NLB still containing active targets in the target group (terminate the ECS service and delete the LB target group subsequently), or API Gateway still has a VPC Link that references the NLB. You'll need to delete the VPC Link before the NLB can be deleted too.

**Comment by emcginty70** [comment] 2019-03-29 16:09
Target Groups removed
API gateway has been 100% deleted
ECS is 100% deleted

When I try to delete the NLB, 'arn:aws:elasticloadbalancing:us-east-1:281174624655:loadbalancer/net/mysfits-nlb/eb9c86e32cfc83b6' cannot be deleted because it is currently associated with another service

My suspicion is that it's the VPC Endpoint Service because it has the following, arn:aws:elasticloadbalancing:us-east-1:281174624655:loadbalancer/net/mysfits-nlb/eb9c86e32cfc83b6

I attempted to unassociate the NLB from the Endpoint with no luck.

**Comment by abaird986** [comment] 2019-03-29 16:20
Can you ensure the VPC Link has been deleted in API Gateway? It's listed in the API Gateway console as a top-level resource on the service home page, not as part of a particular API.

**Comment by emcginty70** [comment] 2019-03-29 18:31
Here's what fixed it.  I had deleted the api but not the VPC Link so I didn't have the menu anymore, just the stand "get started" page.  So I imported the sample pet store to get the menu to appear again and then I was able to delete the VPC Link and then the NLB.

**Comment by abaird986** [comment] 2019-04-03 18:33
Ah, I have seen that before. Would you be willing to go into the AWS Console on the API Gateway home page and click the "Feedback" button at the bottom left of the page?  It would be great to have a customer indicate the experience you had here when the API Gateway page defaulted back to the Welcome/Getting Started experience even though you had resources still existing.

Closing the issue as it's been resolved for you.

**Closed by abaird986** 2019-04-03 18:33 UTC

**Comment by rahul-satal** [comment] 2019-11-27 13:05
Just follow the instruction - https://aws.amazon.com/premiumsupport/knowledge-center/vpc-detach-or-delete-eni/
