### ISSUE TITLE
Load balancer cannot be reached for testing module 2

### ISSUE THREAD

**Issue by dmauk** [aws-samples/aws-modern-application-workshop#14] opened 2018-07-27 03:59 UTC
I followed your steps exactly for module 2 three separate times but upon visiting the nlb, I always reach a blank page even with /mysfits. If I upload to s3 and view the website, the mysfits don't populate and I can see the load balancer returning 404 not found.

Everything is healthy when I visit the amazon console.

**Comment by jschwarzwalder** [comment] 2018-07-29 03:31
Check to make sure you are not using https:// 
I use https everywhere and it was causing me issues. 

Does it work when you previewed it inside Cloud9?

**Comment by abaird986** [comment] 2018-08-01 19:09
@dmauk  - typically the problem that we've seen here is related to either the private/public subnets that are assigned to the nlb and ecs tasks/service. Be sure the public subnets are assigned to the nlb and the private subnets are assigned to the ecs tasks/service.

The best place to debug further is if you review the ECS console, click on your cluster, then your service, then the running task see the Logs tab.  Within the service and tasks tabs, you'll also be able to see events, in case there are failures occurring when trying to create/start your tasks in ECS.

**Comment by mrjhnsn** [comment] 2018-08-04 20:29
I have been stuck on the same part for the last week, everything I have tried does not work.
The running task keeps getting stuck on "pending".... 
When I go to logs it shows no running tasks.

**Comment by abaird986** [comment] 2018-08-06 18:59
Sorry you're hitting some walls @mrjhnsn, can you further explore the ECS console?  If you view the "Stopped" filter within the Tasks tab, can you see any tasks that attempted to start and immediately stopped with an error reported?  Or, within the Events tab, is anything reported there?  If you are able to see tasks go from Pending and then disappearing, you should be able to find a reported error message within the ECS console for why they're failing to get to the Running state.

This is usually related to ECS being unable to pull the Image from ECR (root cause could be related to the task-definition.json file used to create the Task Definition, or IAM role isn't assigned appropriately and the service is getting an Access Denied error when pulling the image).

**Comment by mrjhnsn** [comment] 2018-08-06 22:53
Yeah, I was able to figure out what the problem was. The docker container was not being pulled successfully by the task due to an Access Denied error. Everything I did to try and fix it wasn't working so I just tore down the whole thing and will start fresh on the next run.

**Comment by abaird986** [comment] 2018-08-07 16:51
Ah, sorry about that.  If everything seemed to be correctly configured, be sure to run the command in Module 2 that creates an ECS Service Linked Role.  That's what allows the ECS Service itself to act on resources within your account (like pull images).  It's accomplished with the below command (also described in Module 2, so you can wait to get to that portion again before running it):
 
```
aws iam create-service-linked-role --aws-service-name ecs.amazonaws.com
```

I'm going to close this issue for now, but don't hesitate to re-open it or another if you run into the same issue.

**Closed by abaird986** 2018-08-07 16:51 UTC

**Comment by ArtemKushnerov** [comment] 2019-06-12 10:24
Hi @abaird986 . I'm facing similar issue, load balancer is not connecting request - expires with a timeout. I tried your suggestions: seems like I got it right with subnets, and also I checked a running task in a cluster via aws console, it shows a bunch of 200 health check responses, but not mysfits responses. How can I investigate further? Is there a way to see some logs on load balancer itself?

**Comment by ckygel** [comment] 2019-12-04 21:47
@abaird986 I found the following error message in events section of ECS cluster:

> service MythicalMysfits-Service failed to launch a task with (error ECS was unable to assume the role 'arn:aws:iam::171716118564:role/ECSTaskRole' that was provided for this task. Please verify that the role being passed has the proper trust relationship and permissions and that your IAM user has permissions to pass this role.).

But when I try 
```
aws iam create-service-linked-role --aws-service-name ecs.amazonaws.com
```
In Cloud9 console, it says

> An error occurred (InvalidInput) when calling the CreateServiceLinkedRole operation: Service role name AWSServiceRoleForECS has been taken in this account, please try a different suffix.


I am confused what's happening here...it's like a quantum superposition where you have a role but also don't have a role and so you can't create the role again(?). Could you help me resolve this issuse?

**Comment by abaird986** [comment] 2019-12-04 22:06
Hi @0xckylee - the error message makes me think the full ECSTaskArn pasted in the task definition is incorrect.  Because these are created by cloudformation, I would expect to see an appended string from the stackId.  The full ARN would look similar to the following (value for 12 digit AccoutnId and then random string assigned by CloudFormation as the suffix):
arn:aws:iam::[AccountId]:role/MythicalMysfitsCoreStack-ECSTaskRole-[ABC12345]

**Comment by ckygel** [comment] 2019-12-05 02:06
Resolved the problem! @abaird986  Thank you for quick response :) @mrjhnsn I had this Docker image pull access denied error as well. For people facing this issue in the future, please check the following:

1. In the taskdefinition.json, I had ECSTaskArn, ECSService role and whole lot of other REPLACE_VALUE as literally "ECSTaskARN" rather than pasting the value of ARN. It should be "arn:aws:iam:XXXX" instead.
2. For those getting "failing to pull Docker images" error, also check whether in taskdefinition.json "image" field you've typed in is "latest" or something else  -.- I thought docker image tag was just referring to "latest". Head to ECR and copy the URI of repo, paste it into "image" field in taskdefinition.json
3. Run `aws ecs register-task-definition --cli-input-json file://~/environment/aws-modern-application-workshop/module-2/aws-cli/task-definition.json`

(from this point on, I'm not sure if this is the right procedure, but it worked)
4. Since you've updated task-definition, there will be a newer version of task definition in ECS > Task Definition. 
5. Deregister the older version
6. Click on the latest version > Actions > Run Task
7. Click on the latest version > Actions > Update Service
8. Repeat 6 & 7, wait for a while

**Comment by markdavis33** [comment] 2020-08-28 20:09
@abaird986 I'm having the same issue as described [above](https://github.com/aws-samples/aws-modern-application-workshop/issues/14#issue-345082706), wondering if you can help?

DETAILS:

In Module 2B, step 5, part C ("test the service"), when I run this command:

`mysfits-nlb-8e6eef167c117a26.elb.us-east-1.amazonaws.com/mysfits`

I'm getting this error:

`bash: mysfits-nlb-8e6eef167c117a26.elb.us-east-1.amazonaws.com/mysfits: No such file or directory`
