### ISSUE TITLE
In Golang Branch, CodeBuild, go get "missing git command"

### ISSUE THREAD

**Issue by ThisIsFred** [aws-samples/aws-modern-application-workshop#127] opened 2019-08-20 23:47 UTC
At the end of module-3, after "git push" to CodePipeline and during the "CodeBuild" step, build fails, apparently due to missing git installation. I do not know how to install git on the build server. Help is appreciated. Build log reads:

Step 5/13 : RUN go get -d -v 
 ---> Running in d5c179f9eca0 
·[91mgithub.com/aws/aws-sdk-go (download) 
·[0m·[91mgo: missing Git command. See https://golang.org/s/gogetcmd 
package github.com/aws/aws-sdk-go/aws: exec: "git": executable file not found in $PATH
Thanks

**Comment by abaird986** [comment] 2019-08-21 14:42
@dave-malone + @Doug-AWS  - can either of you guys take a look at this one?

**Comment by dave-malone** [comment] 2019-09-04 18:57
@ThisIsFred can you please confirm that you ran through all of module 2 without errors before attempting module 3? I'm unable to reproduce the issue as long as I've completed all of module 2. 

The CodeBuild step is occurring as part of the Docker container build, which should be self-contained with all of the necessary modules. 

I was able to pass the CodeBuild step in the CodePipeline, and I was also able to build the Docker image standalone in my Cloud9 environment without encountering the error you mentioned above.

**Comment by gtrafimenkov** [comment] 2019-09-14 11:49
The issue is here: https://github.com/aws-samples/aws-modern-application-workshop/blob/go/module-3/README.md#copy-the-updated-go-service-code.  It is also necessary to copy updated Dockerfile

**Comment by mfaust-dd** [comment] 2020-01-06 01:26
Thank you very much, @gtrafimenkov. I was stuck on the same thing.

**Comment by abaird986** [comment] 2021-04-27 16:29
Closing this with the instruction clarification provided above. Please submit a PR if you feel this warrants a change in the README. Thanks!

**Closed by abaird986** 2021-04-27 16:29 UTC
