### ISSUE TITLE
Unable to register user via Cognito client

### ISSUE THREAD

**Issue by kittlsk** [aws-samples/aws-modern-application-workshop#100] opened 2019-04-15 02:58 UTC
Hi I've completed this demo - https://github.com/aws-samples/aws-modern-application-workshop/tree/java/module-4 and when I tried to register a new user, it keeps prompting me Network Error!  I've changed the Cognito password policy to the most simplest requirement still not managed to register any user.  Is anyone facing the same problem?

**Comment by Doug-AWS** [comment] 2019-04-15 13:09
Could you paste the entire error message into this issue?

**Comment by kittlsk** [comment] 2019-04-16 00:46
Hi Doug thanks for your reply.  I don't see any related error shown in my CloudTrail configured to read my s3 bucket.  Is there any additional step that I need to do to enable the trail for Cognito client?

**Comment by Doug-AWS** [comment] 2019-04-16 13:58
I only worked on the Go port. The person who worked on the Java port is off on maternity leave. Not sure who else is available to help.

**Comment by abaird986** [comment] 2019-04-16 14:04
I can review here @Doug-AWS 

@kittlsk  - could you please open up your browser's web console?  That will provide you the ability to see the network errors that are possibly being returned by your APIs or the Cognito service when trying to register a user.

See here for Chrome:
https://developers.google.com/web/tools/chrome-devtools/console/

And here for FF:
https://developer.mozilla.org/en-US/docs/Tools/Web_Console/Opening_the_Web_Console

Once you've done that, could you please share the error message being returned when user registration fails?

**Comment by chenhan1218** [comment] 2019-04-25 10:29
@abaird986 
My console output while user registration fails:

```
OPTIONS https://cognito-idp.replace.amazonaws.com/ net::ERR_NAME_NOT_RESOLVED
e.request	@	amazon-cognito-identity.min.js:120
e.signUp	@	amazon-cognito-identity.min.js:120
(anonymous)	@	register.html:74
dispatch	@	jquery.min.js:3
q.handle	@	jquery.min.js:3
﻿```

**Comment by chenhan1218** [comment] 2019-04-30 08:37
I've figured out the root cause of the problem: There are two more files need to be modified which is not mentioned in the workshop module-4:

1. replace cognitoUserPoolId and cognitoUserPoolClientId in confirm.html
https://github.com/aws-samples/aws-modern-application-workshop/blob/b8ebf4020b2e73d2f5f66ce64dc2648f947d380b/module-4/web/confirm.html#L39

2. replace cognitoUserPoolId and cognitoUserPoolClientId in register.html
https://github.com/aws-samples/aws-modern-application-workshop/blob/b8ebf4020b2e73d2f5f66ce64dc2648f947d380b/module-4/web/register.html#L46

**Comment by chenhan1218** [comment] 2019-04-30 08:47
So this is not a issue after I correctly modified the files by following the steps module-4.

**Comment by abaird986** [comment] 2019-04-30 19:16
Ah, glad you found your root cause @chenhan1218 !  Going to close this out.

**Closed by abaird986** 2019-04-30 19:16 UTC
